/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package center.indus.Application.homeWindow;

import center.indus.Application.DataFetcher;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdul Wahid
 */
public class ClassesWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClassesWindow
     */
    public ClassesWindow(String cName) {
        
        initComponents();
        method();
        className.setText(cName);
    }
    
    public void method(){
        dataFetcher = new DataFetcher("centerTable");
        data = dataFetcher.studentData();
        defTableModel = (DefaultTableModel) detailTable.getModel();
        
       
        for(int i = 0; i< data.size(); i++){
            temp = (Student) data.get(i);
            defTableModel.addRow(new Object[]{temp.getRollNo(),temp.getName(),temp.getFather(),temp.getFee()});
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WAR
    /**NING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classWindowPanel = new javax.swing.JPanel();
        classWindowBar = new javax.swing.JPanel();
        classTitle = new javax.swing.JLabel();
        className = new javax.swing.JLabel();
        classWindowArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        classWindowPanel.setLayout(new javax.swing.BoxLayout(classWindowPanel, javax.swing.BoxLayout.Y_AXIS));

        classWindowBar.setBackground(new java.awt.Color(51, 51, 51));
        classWindowBar.setMaximumSize(new java.awt.Dimension(950, 45));
        classWindowBar.setMinimumSize(new java.awt.Dimension(950, 45));
        classWindowBar.setPreferredSize(new java.awt.Dimension(950, 45));
        classWindowBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        classTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        classTitle.setForeground(new java.awt.Color(255, 255, 255));
        classTitle.setText("Class   ");
        classWindowBar.add(classTitle);

        className.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        className.setForeground(new java.awt.Color(255, 255, 255));
        classWindowBar.add(className);

        classWindowPanel.add(classWindowBar);

        classWindowArea.setBackground(new java.awt.Color(255, 255, 255));

        detailTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Roll No", "Name", "Father", "Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(detailTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Number of Students");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Roll No", "Name", "Father", "Fee"
            }
        ));
        jScrollPane2.setViewportView(searchTable);

        javax.swing.GroupLayout classWindowAreaLayout = new javax.swing.GroupLayout(classWindowArea);
        classWindowArea.setLayout(classWindowAreaLayout);
        classWindowAreaLayout.setHorizontalGroup(
            classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classWindowAreaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(classWindowAreaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(classWindowAreaLayout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        classWindowAreaLayout.setVerticalGroup(
            classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classWindowAreaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classWindowAreaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(classWindowAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(classWindowAreaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        classWindowPanel.add(classWindowArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dataFetcher = new DataFetcher("centerTable");
        hashtable = dataFetcher.studentHashData();
        temp2 = (Student) hashtable.get(search.getText());
        defTableModelSearch = (DefaultTableModel) searchTable.getModel();
        defTableModelSearch.addRow(new Object[]{temp2.getRollNo(),temp2.getName(),temp2.getFather(),temp2.getFee()});
        dataFetcher = null;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private Student temp,temp2;
    private ArrayList data;
    private Hashtable hashtable;
    private DataFetcher dataFetcher;
    private DefaultTableModel defTableModel ;
    private DefaultTableModel defTableModelSearch;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel className;
    private javax.swing.JLabel classTitle;
    private javax.swing.JPanel classWindowArea;
    private javax.swing.JPanel classWindowBar;
    private javax.swing.JPanel classWindowPanel;
    private javax.swing.JTable detailTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JTable searchTable;
    // End of variables declaration//GEN-END:variables
}
