package center.indus.Application.homeWindow;

import java.awt.Color;

import javax.swing.JPanel;

public class HomeWindow extends javax.swing.JFrame {

    /** Creates new form HomeWindow */
    public HomeWindow() {
        initComponents();
        openCardWindow(admissionCardPanel);
    }
    
    public void openCard(JPanel cardPanel){
      
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeWindowMainPanel = new javax.swing.JPanel();
        titleBarPanel = new javax.swing.JPanel();
        menuItemsPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        admissionButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        classesButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardsAreaPanel = new javax.swing.JPanel();
        cardsPanel = new javax.swing.JPanel();
        classesCardPanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel16 = new javax.swing.JPanel();
        ixClassPanel = new javax.swing.JPanel();
        ixIconPanel = new javax.swing.JPanel();
        ixIcon = new javax.swing.JLabel();
        ixSeparator = new javax.swing.JSeparator();
        ixClassDetails = new javax.swing.JPanel();
        ixClass = new javax.swing.JLabel();
        ixClassName = new javax.swing.JLabel();
        ixStudents = new javax.swing.JLabel();
        ixStudentsNumber = new javax.swing.JLabel();
        xClassPanel = new javax.swing.JPanel();
        xIconPanel = new javax.swing.JPanel();
        xIcon = new javax.swing.JLabel();
        xSeparator = new javax.swing.JSeparator();
        xClassDetails = new javax.swing.JPanel();
        xClass = new javax.swing.JLabel();
        xClassName = new javax.swing.JLabel();
        xStudents = new javax.swing.JLabel();
        xStudentsNumber = new javax.swing.JLabel();
        xiPEClassPanel = new javax.swing.JPanel();
        xiPEIconPanel = new javax.swing.JPanel();
        xiPEIcon = new javax.swing.JLabel();
        xiPESeparator = new javax.swing.JSeparator();
        xiPEClassDetails = new javax.swing.JPanel();
        xiPEClass = new javax.swing.JLabel();
        xiPEClassName = new javax.swing.JLabel();
        xiPEStudents = new javax.swing.JLabel();
        xiPEStudentsNumber = new javax.swing.JLabel();
        xiPMClassPanel = new javax.swing.JPanel();
        xiPMIconPanel = new javax.swing.JPanel();
        xiPMIcon = new javax.swing.JLabel();
        xiPMSeparator = new javax.swing.JSeparator();
        xiPMClassDetails = new javax.swing.JPanel();
        xiPMClass = new javax.swing.JLabel();
        xiPMClassName = new javax.swing.JLabel();
        xiPMStudents = new javax.swing.JLabel();
        xiPMStudentsNumber = new javax.swing.JLabel();
        xiiPEClassPanel = new javax.swing.JPanel();
        xiiPEIconPanel = new javax.swing.JPanel();
        xiiPEIcon = new javax.swing.JLabel();
        xiiPESeparator = new javax.swing.JSeparator();
        xiiPEClassDetails = new javax.swing.JPanel();
        xiiPEClass = new javax.swing.JLabel();
        xiiPEClassName = new javax.swing.JLabel();
        xiiPEStudents = new javax.swing.JLabel();
        xiiPEStudentsNumber = new javax.swing.JLabel();
        xiiPMClassPanel = new javax.swing.JPanel();
        xiiPMIconPanel = new javax.swing.JPanel();
        xiiPMIcon = new javax.swing.JLabel();
        xiiPMSeparator = new javax.swing.JSeparator();
        xiiPMClassDetails = new javax.swing.JPanel();
        xiiPMClass = new javax.swing.JLabel();
        xiiPMClassName = new javax.swing.JLabel();
        xiiPMStudents = new javax.swing.JLabel();
        xiiPMStudentNumber = new javax.swing.JLabel();
        admissionCardPanel = new javax.swing.JPanel();
        admissionTitleBar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        admissionSeparator = new javax.swing.JSeparator();
        admissionCardArea = new javax.swing.JPanel();
        rollNo = new javax.swing.JLabel();
        rollNoEditText = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        nameEditText = new javax.swing.JTextField();
        father = new javax.swing.JLabel();
        fatherEditText = new javax.swing.JTextField();
        fee = new javax.swing.JLabel();
        feeEditText = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 510));
        setMinimumSize(new java.awt.Dimension(960, 510));
        setUndecorated(true);

        homeWindowMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        homeWindowMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homeWindowMainPanel.setMaximumSize(new java.awt.Dimension(960, 510));
        homeWindowMainPanel.setMinimumSize(new java.awt.Dimension(960, 510));
        homeWindowMainPanel.setPreferredSize(new java.awt.Dimension(960, 510));
        homeWindowMainPanel.setLayout(new javax.swing.BoxLayout(homeWindowMainPanel, javax.swing.BoxLayout.Y_AXIS));

        titleBarPanel.setBackground(new java.awt.Color(51, 51, 51));
        titleBarPanel.setMaximumSize(new java.awt.Dimension(959, 50));
        titleBarPanel.setMinimumSize(new java.awt.Dimension(959, 50));
        titleBarPanel.setPreferredSize(new java.awt.Dimension(949, 50));

        javax.swing.GroupLayout titleBarPanelLayout = new javax.swing.GroupLayout(titleBarPanel);
        titleBarPanel.setLayout(titleBarPanelLayout);
        titleBarPanelLayout.setHorizontalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        titleBarPanelLayout.setVerticalGroup(
            titleBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        homeWindowMainPanel.add(titleBarPanel);

        menuItemsPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuItemsPanel.setMaximumSize(new java.awt.Dimension(959, 455));
        menuItemsPanel.setMinimumSize(new java.awt.Dimension(959, 455));
        menuItemsPanel.setPreferredSize(new java.awt.Dimension(959, 455));
        menuItemsPanel.setLayout(new javax.swing.BoxLayout(menuItemsPanel, javax.swing.BoxLayout.X_AXIS));

        menuPanel.setBackground(new java.awt.Color(82, 82, 82));
        menuPanel.setMaximumSize(new java.awt.Dimension(200, 458));
        menuPanel.setMinimumSize(new java.awt.Dimension(200, 458));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 458));
        menuPanel.setRequestFocusEnabled(false);
        menuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jSeparator1.setBackground(new java.awt.Color(82, 82, 82));
        jSeparator1.setMaximumSize(new java.awt.Dimension(199, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(199, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(199, 1));
        menuPanel.add(jSeparator1);

        admissionButton.setBackground(new java.awt.Color(51, 51, 51));
        admissionButton.setMaximumSize(new java.awt.Dimension(199, 40));
        admissionButton.setMinimumSize(new java.awt.Dimension(199, 40));
        admissionButton.setPreferredSize(new java.awt.Dimension(199, 40));
        admissionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admissionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admissionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admissionButtonMouseExited(evt);
            }
        });
        admissionButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admission Icon 32.png"))); // NOI18N
        admissionButton.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admission");
        admissionButton.add(jLabel2);

        menuPanel.add(admissionButton);

        jSeparator2.setBackground(new java.awt.Color(82, 82, 82));
        jSeparator2.setMaximumSize(new java.awt.Dimension(199, 1));
        jSeparator2.setMinimumSize(new java.awt.Dimension(199, 1));
        jSeparator2.setPreferredSize(new java.awt.Dimension(199, 1));
        menuPanel.add(jSeparator2);

        classesButton.setBackground(new java.awt.Color(51, 51, 51));
        classesButton.setMaximumSize(new java.awt.Dimension(199, 40));
        classesButton.setMinimumSize(new java.awt.Dimension(199, 40));
        classesButton.setPreferredSize(new java.awt.Dimension(199, 40));
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                classesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                classesButtonMouseExited(evt);
            }
        });
        classesButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Classroom Icon 32.png"))); // NOI18N
        classesButton.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Classes");
        classesButton.add(jLabel4);

        menuPanel.add(classesButton);

        menuItemsPanel.add(menuPanel);

        cardsAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardsAreaPanel.setMaximumSize(new java.awt.Dimension(759, 455));
        cardsAreaPanel.setMinimumSize(new java.awt.Dimension(759, 455));
        cardsAreaPanel.setPreferredSize(new java.awt.Dimension(759, 455));
        cardsAreaPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        cardsPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardsPanel.setMaximumSize(new java.awt.Dimension(736, 435));
        cardsPanel.setMinimumSize(new java.awt.Dimension(736, 435));
        cardsPanel.setPreferredSize(new java.awt.Dimension(736, 435));
        cardsPanel.setLayout(new java.awt.CardLayout());

        classesCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        classesCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        classesCardPanel.setMaximumSize(new java.awt.Dimension(736, 440));
        classesCardPanel.setMinimumSize(new java.awt.Dimension(736, 440));
        classesCardPanel.setPreferredSize(new java.awt.Dimension(736, 440));
        classesCardPanel.setLayout(new javax.swing.BoxLayout(classesCardPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel15.setBackground(new java.awt.Color(231, 244, 234));
        jPanel15.setMaximumSize(new java.awt.Dimension(736, 40));
        jPanel15.setMinimumSize(new java.awt.Dimension(736, 40));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Classroom Icon 32.png"))); // NOI18N
        jPanel15.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Classes");
        jPanel15.add(jLabel8);

        classesCardPanel.add(jPanel15);

        jSeparator4.setMaximumSize(new java.awt.Dimension(736, 10));
        jSeparator4.setMinimumSize(new java.awt.Dimension(736, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(736, 10));
        classesCardPanel.add(jSeparator4);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMaximumSize(new java.awt.Dimension(716, 370));
        jPanel16.setMinimumSize(new java.awt.Dimension(716, 370));
        jPanel16.setPreferredSize(new java.awt.Dimension(716, 370));
        jPanel16.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        ixClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        ixClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        ixClassPanel.setMaximumSize(new java.awt.Dimension(232, 182));
        ixClassPanel.setMinimumSize(new java.awt.Dimension(232, 182));
        ixClassPanel.setPreferredSize(new java.awt.Dimension(232, 180));
        ixClassPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ixClassPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ixClassPanelMouseEntered(evt);
            }
        });
        ixClassPanel.setLayout(new javax.swing.BoxLayout(ixClassPanel, javax.swing.BoxLayout.X_AXIS));

        ixIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        ixIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        ixIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        ixIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        ixIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ixIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N
        ixIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ixIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ixIconPanelLayout = new javax.swing.GroupLayout(ixIconPanel);
        ixIconPanel.setLayout(ixIconPanelLayout);
        ixIconPanelLayout.setHorizontalGroup(
            ixIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ixIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        ixIconPanelLayout.setVerticalGroup(
            ixIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ixIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        ixClassPanel.add(ixIconPanel);

        ixSeparator.setForeground(new java.awt.Color(204, 204, 204));
        ixSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        ixSeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        ixSeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        ixSeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        ixClassPanel.add(ixSeparator);

        ixClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        ixClassDetails.setMaximumSize(new java.awt.Dimension(114, 180));
        ixClassDetails.setMinimumSize(new java.awt.Dimension(114, 180));
        ixClassDetails.setPreferredSize(new java.awt.Dimension(114, 180));
        ixClassDetails.setLayout(new javax.swing.BoxLayout(ixClassDetails, javax.swing.BoxLayout.Y_AXIS));

        ixClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ixClass.setText("  Class");
        ixClass.setMaximumSize(new java.awt.Dimension(115, 30));
        ixClass.setMinimumSize(new java.awt.Dimension(115, 30));
        ixClass.setPreferredSize(new java.awt.Dimension(115, 30));
        ixClassDetails.add(ixClass);

        ixClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ixClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ixClassName.setText("IX");
        ixClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        ixClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        ixClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        ixClassDetails.add(ixClassName);

        ixStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ixStudents.setText("  Students");
        ixStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        ixStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        ixStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        ixClassDetails.add(ixStudents);

        ixStudentsNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ixStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ixStudentsNumber.setText("0");
        ixStudentsNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        ixStudentsNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        ixStudentsNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        ixClassDetails.add(ixStudentsNumber);

        ixClassPanel.add(ixClassDetails);

        jPanel16.add(ixClassPanel);

        xClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        xClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xClassPanel.setLayout(new javax.swing.BoxLayout(xClassPanel, javax.swing.BoxLayout.X_AXIS));

        xIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        xIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        xIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        xIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        xIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N
        xIcon.setMaximumSize(new java.awt.Dimension(114, 180));
        xIcon.setMinimumSize(new java.awt.Dimension(114, 180));
        xIcon.setPreferredSize(new java.awt.Dimension(114, 180));

        javax.swing.GroupLayout xIconPanelLayout = new javax.swing.GroupLayout(xIconPanel);
        xIconPanel.setLayout(xIconPanelLayout);
        xIconPanelLayout.setHorizontalGroup(
            xIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        xIconPanelLayout.setVerticalGroup(
            xIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xIconPanelLayout.createSequentialGroup()
                .addComponent(xIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        xClassPanel.add(xIconPanel);

        xSeparator.setForeground(new java.awt.Color(204, 204, 204));
        xSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        xSeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        xSeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        xSeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        xClassPanel.add(xSeparator);

        xClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        xClassDetails.setMaximumSize(new java.awt.Dimension(115, 178));
        xClassDetails.setMinimumSize(new java.awt.Dimension(115, 178));
        xClassDetails.setPreferredSize(new java.awt.Dimension(115, 178));
        xClassDetails.setLayout(new javax.swing.BoxLayout(xClassDetails, javax.swing.BoxLayout.Y_AXIS));

        xClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xClass.setText("  Class");
        xClass.setMaximumSize(new java.awt.Dimension(115, 30));
        xClass.setMinimumSize(new java.awt.Dimension(115, 30));
        xClass.setPreferredSize(new java.awt.Dimension(115, 30));
        xClassDetails.add(xClass);

        xClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xClassName.setText("X");
        xClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        xClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        xClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        xClassDetails.add(xClassName);

        xStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xStudents.setText("  Students");
        xStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        xStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        xStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        xClassDetails.add(xStudents);

        xStudentsNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xStudentsNumber.setText("0");
        xStudentsNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        xStudentsNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        xStudentsNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        xClassDetails.add(xStudentsNumber);

        xClassPanel.add(xClassDetails);

        jPanel16.add(xClassPanel);

        xiPEClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiPEClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xiPEClassPanel.setLayout(new javax.swing.BoxLayout(xiPEClassPanel, javax.swing.BoxLayout.X_AXIS));

        xiPEIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiPEIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        xiPEIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        xiPEIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        xiPEIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPEIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N

        javax.swing.GroupLayout xiPEIconPanelLayout = new javax.swing.GroupLayout(xiPEIconPanel);
        xiPEIconPanel.setLayout(xiPEIconPanelLayout);
        xiPEIconPanelLayout.setHorizontalGroup(
            xiPEIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiPEIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        xiPEIconPanelLayout.setVerticalGroup(
            xiPEIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiPEIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        xiPEClassPanel.add(xiPEIconPanel);

        xiPESeparator.setForeground(new java.awt.Color(204, 204, 204));
        xiPESeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        xiPESeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        xiPESeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        xiPESeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        xiPEClassPanel.add(xiPESeparator);

        xiPEClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        xiPEClassDetails.setMaximumSize(new java.awt.Dimension(114, 180));
        xiPEClassDetails.setMinimumSize(new java.awt.Dimension(114, 180));
        xiPEClassDetails.setLayout(new javax.swing.BoxLayout(xiPEClassDetails, javax.swing.BoxLayout.Y_AXIS));

        xiPEClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiPEClass.setText("  Class");
        xiPEClass.setMaximumSize(new java.awt.Dimension(115, 30));
        xiPEClass.setMinimumSize(new java.awt.Dimension(115, 30));
        xiPEClass.setPreferredSize(new java.awt.Dimension(115, 30));
        xiPEClassDetails.add(xiPEClass);

        xiPEClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiPEClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPEClassName.setText("XI P.E");
        xiPEClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        xiPEClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        xiPEClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        xiPEClassDetails.add(xiPEClassName);

        xiPEStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiPEStudents.setText("  Students");
        xiPEStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        xiPEStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        xiPEStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        xiPEClassDetails.add(xiPEStudents);

        xiPEStudentsNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiPEStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPEStudentsNumber.setText("0");
        xiPEStudentsNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xiPEStudentsNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        xiPEStudentsNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        xiPEStudentsNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        xiPEClassDetails.add(xiPEStudentsNumber);

        xiPEClassPanel.add(xiPEClassDetails);

        jPanel16.add(xiPEClassPanel);

        xiPMClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiPMClassPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        xiPMClassPanel.setLayout(new javax.swing.BoxLayout(xiPMClassPanel, javax.swing.BoxLayout.X_AXIS));

        xiPMIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiPMIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        xiPMIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        xiPMIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        xiPMIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPMIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N

        javax.swing.GroupLayout xiPMIconPanelLayout = new javax.swing.GroupLayout(xiPMIconPanel);
        xiPMIconPanel.setLayout(xiPMIconPanelLayout);
        xiPMIconPanelLayout.setHorizontalGroup(
            xiPMIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiPMIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        xiPMIconPanelLayout.setVerticalGroup(
            xiPMIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiPMIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        xiPMClassPanel.add(xiPMIconPanel);

        xiPMSeparator.setForeground(new java.awt.Color(204, 204, 204));
        xiPMSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        xiPMSeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        xiPMSeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        xiPMSeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        xiPMClassPanel.add(xiPMSeparator);

        xiPMClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        xiPMClassDetails.setMaximumSize(new java.awt.Dimension(114, 180));
        xiPMClassDetails.setMinimumSize(new java.awt.Dimension(114, 180));
        xiPMClassDetails.setLayout(new javax.swing.BoxLayout(xiPMClassDetails, javax.swing.BoxLayout.Y_AXIS));

        xiPMClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiPMClass.setText("  Class");
        xiPMClass.setMaximumSize(new java.awt.Dimension(115, 30));
        xiPMClassDetails.add(xiPMClass);

        xiPMClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiPMClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPMClassName.setText("XI P.M");
        xiPMClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        xiPMClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        xiPMClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        xiPMClassDetails.add(xiPMClassName);

        xiPMStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiPMStudents.setText("  Students");
        xiPMStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        xiPMStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        xiPMStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        xiPMClassDetails.add(xiPMStudents);

        xiPMStudentsNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiPMStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiPMStudentsNumber.setText("0");
        xiPMStudentsNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        xiPMStudentsNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        xiPMStudentsNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        xiPMClassDetails.add(xiPMStudentsNumber);

        xiPMClassPanel.add(xiPMClassDetails);

        jPanel16.add(xiPMClassPanel);

        xiiPEClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiiPEClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xiiPEClassPanel.setLayout(new javax.swing.BoxLayout(xiiPEClassPanel, javax.swing.BoxLayout.LINE_AXIS));

        xiiPEIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiiPEIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        xiiPEIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        xiiPEIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        xiiPEIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPEIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N

        javax.swing.GroupLayout xiiPEIconPanelLayout = new javax.swing.GroupLayout(xiiPEIconPanel);
        xiiPEIconPanel.setLayout(xiiPEIconPanelLayout);
        xiiPEIconPanelLayout.setHorizontalGroup(
            xiiPEIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiiPEIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        xiiPEIconPanelLayout.setVerticalGroup(
            xiiPEIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiiPEIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        xiiPEClassPanel.add(xiiPEIconPanel);

        xiiPESeparator.setForeground(new java.awt.Color(204, 204, 204));
        xiiPESeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        xiiPESeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        xiiPESeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        xiiPESeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        xiiPEClassPanel.add(xiiPESeparator);

        xiiPEClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        xiiPEClassDetails.setMaximumSize(new java.awt.Dimension(114, 180));
        xiiPEClassDetails.setMinimumSize(new java.awt.Dimension(114, 180));
        xiiPEClassDetails.setLayout(new javax.swing.BoxLayout(xiiPEClassDetails, javax.swing.BoxLayout.Y_AXIS));

        xiiPEClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiiPEClass.setText("  Class");
        xiiPEClass.setMaximumSize(new java.awt.Dimension(115, 30));
        xiiPEClass.setMinimumSize(new java.awt.Dimension(115, 30));
        xiiPEClass.setPreferredSize(new java.awt.Dimension(115, 30));
        xiiPEClassDetails.add(xiiPEClass);

        xiiPEClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiiPEClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPEClassName.setText("XII P.E");
        xiiPEClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        xiiPEClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        xiiPEClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        xiiPEClassDetails.add(xiiPEClassName);

        xiiPEStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiiPEStudents.setText("  Students");
        xiiPEStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        xiiPEStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        xiiPEStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        xiiPEClassDetails.add(xiiPEStudents);

        xiiPEStudentsNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiiPEStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPEStudentsNumber.setText("0");
        xiiPEStudentsNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        xiiPEStudentsNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        xiiPEStudentsNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        xiiPEClassDetails.add(xiiPEStudentsNumber);

        xiiPEClassPanel.add(xiiPEClassDetails);

        jPanel16.add(xiiPEClassPanel);

        xiiPMClassPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiiPMClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xiiPMClassPanel.setLayout(new javax.swing.BoxLayout(xiiPMClassPanel, javax.swing.BoxLayout.X_AXIS));

        xiiPMIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        xiiPMIconPanel.setMaximumSize(new java.awt.Dimension(114, 180));
        xiiPMIconPanel.setMinimumSize(new java.awt.Dimension(114, 180));
        xiiPMIconPanel.setPreferredSize(new java.awt.Dimension(114, 180));

        xiiPMIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPMIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person Icon.png"))); // NOI18N

        javax.swing.GroupLayout xiiPMIconPanelLayout = new javax.swing.GroupLayout(xiiPMIconPanel);
        xiiPMIconPanel.setLayout(xiiPMIconPanelLayout);
        xiiPMIconPanelLayout.setHorizontalGroup(
            xiiPMIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiiPMIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        xiiPMIconPanelLayout.setVerticalGroup(
            xiiPMIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xiiPMIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        xiiPMClassPanel.add(xiiPMIconPanel);

        xiiPMSeparator.setForeground(new java.awt.Color(204, 204, 204));
        xiiPMSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        xiiPMSeparator.setMaximumSize(new java.awt.Dimension(2, 180));
        xiiPMSeparator.setMinimumSize(new java.awt.Dimension(2, 180));
        xiiPMSeparator.setPreferredSize(new java.awt.Dimension(2, 180));
        xiiPMClassPanel.add(xiiPMSeparator);

        xiiPMClassDetails.setBackground(new java.awt.Color(255, 255, 255));
        xiiPMClassDetails.setMaximumSize(new java.awt.Dimension(114, 180));
        xiiPMClassDetails.setMinimumSize(new java.awt.Dimension(114, 180));
        xiiPMClassDetails.setLayout(new javax.swing.BoxLayout(xiiPMClassDetails, javax.swing.BoxLayout.Y_AXIS));

        xiiPMClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiiPMClass.setText("  Class");
        xiiPMClass.setMaximumSize(new java.awt.Dimension(115, 30));
        xiiPMClass.setMinimumSize(new java.awt.Dimension(115, 30));
        xiiPMClass.setPreferredSize(new java.awt.Dimension(115, 30));
        xiiPMClass.setRequestFocusEnabled(false);
        xiiPMClassDetails.add(xiiPMClass);

        xiiPMClassName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiiPMClassName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPMClassName.setText("XII PM");
        xiiPMClassName.setMaximumSize(new java.awt.Dimension(115, 60));
        xiiPMClassName.setMinimumSize(new java.awt.Dimension(115, 60));
        xiiPMClassName.setPreferredSize(new java.awt.Dimension(115, 60));
        xiiPMClassDetails.add(xiiPMClassName);

        xiiPMStudents.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xiiPMStudents.setText("  Students");
        xiiPMStudents.setMaximumSize(new java.awt.Dimension(115, 30));
        xiiPMStudents.setMinimumSize(new java.awt.Dimension(115, 30));
        xiiPMStudents.setPreferredSize(new java.awt.Dimension(115, 30));
        xiiPMClassDetails.add(xiiPMStudents);

        xiiPMStudentNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        xiiPMStudentNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xiiPMStudentNumber.setText("0");
        xiiPMStudentNumber.setMaximumSize(new java.awt.Dimension(115, 60));
        xiiPMStudentNumber.setMinimumSize(new java.awt.Dimension(115, 60));
        xiiPMStudentNumber.setPreferredSize(new java.awt.Dimension(115, 60));
        xiiPMClassDetails.add(xiiPMStudentNumber);

        xiiPMClassPanel.add(xiiPMClassDetails);

        jPanel16.add(xiiPMClassPanel);

        classesCardPanel.add(jPanel16);

        cardsPanel.add(classesCardPanel, "card3");

        admissionCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        admissionCardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        admissionCardPanel.setMaximumSize(new java.awt.Dimension(736, 440));
        admissionCardPanel.setMinimumSize(new java.awt.Dimension(736, 440));
        admissionCardPanel.setPreferredSize(new java.awt.Dimension(736, 440));
        admissionCardPanel.setLayout(new javax.swing.BoxLayout(admissionCardPanel, javax.swing.BoxLayout.Y_AXIS));

        admissionTitleBar.setBackground(new java.awt.Color(231, 244, 234));
        admissionTitleBar.setMaximumSize(new java.awt.Dimension(736, 40));
        admissionTitleBar.setMinimumSize(new java.awt.Dimension(736, 40));
        admissionTitleBar.setPreferredSize(new java.awt.Dimension(736, 40));
        admissionTitleBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admission Icon 32.png"))); // NOI18N
        admissionTitleBar.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Admission");
        admissionTitleBar.add(jLabel6);

        admissionCardPanel.add(admissionTitleBar);

        admissionSeparator.setMaximumSize(new java.awt.Dimension(736, 10));
        admissionSeparator.setMinimumSize(new java.awt.Dimension(736, 10));
        admissionSeparator.setPreferredSize(new java.awt.Dimension(736, 10));
        admissionCardPanel.add(admissionSeparator);

        admissionCardArea.setBackground(new java.awt.Color(255, 255, 255));
        admissionCardArea.setMaximumSize(new java.awt.Dimension(716, 370));
        admissionCardArea.setMinimumSize(new java.awt.Dimension(716, 370));
        admissionCardArea.setPreferredSize(new java.awt.Dimension(716, 370));

        rollNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rollNo.setText("Roll No");

        rollNoEditText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rollNoEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoEditTextActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        name.setText("Name");

        nameEditText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        father.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        father.setText("Father");

        fatherEditText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        fee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fee.setText("Fee");

        feeEditText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.setMaximumSize(new java.awt.Dimension(105, 37));
        jButton1.setMinimumSize(new java.awt.Dimension(105, 37));
        jButton1.setPreferredSize(new java.awt.Dimension(105, 37));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout admissionCardAreaLayout = new javax.swing.GroupLayout(admissionCardArea);
        admissionCardArea.setLayout(admissionCardAreaLayout);
        admissionCardAreaLayout.setHorizontalGroup(
            admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admissionCardAreaLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(father, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rollNo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rollNoEditText)
                        .addComponent(nameEditText)
                        .addComponent(fatherEditText)
                        .addComponent(feeEditText, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(admissionCardAreaLayout.createSequentialGroup()
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        admissionCardAreaLayout.setVerticalGroup(
            admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admissionCardAreaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollNoEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(admissionCardAreaLayout.createSequentialGroup()
                        .addComponent(nameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(father, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatherEditText))
                .addGap(18, 18, 18)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feeEditText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(admissionCardAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        admissionCardPanel.add(admissionCardArea);

        cardsPanel.add(admissionCardPanel, "card2");

        cardsAreaPanel.add(cardsPanel);

        menuItemsPanel.add(cardsAreaPanel);

        homeWindowMainPanel.add(menuItemsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeWindowMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeWindowMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admissionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admissionButtonMouseEntered
        admissionButton.setBackground(Color.BLACK);
    }//GEN-LAST:event_admissionButtonMouseEntered

    private void admissionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admissionButtonMouseExited
        admissionButton.setBackground(Color.decode("0x333333"));
    }//GEN-LAST:event_admissionButtonMouseExited

    private void classesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseEntered
        classesButton.setBackground(Color.BLACK);
    }//GEN-LAST:event_classesButtonMouseEntered

    private void classesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseExited
        classesButton.setBackground(Color.decode("0x333333"));
    }//GEN-LAST:event_classesButtonMouseExited

    private void admissionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admissionButtonMouseClicked
        openCardWindow(admissionCardPanel);
    }//GEN-LAST:event_admissionButtonMouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        openCardWindow(classesCardPanel);
    }//GEN-LAST:event_classesButtonMouseClicked

    private void rollNoEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNoEditTextActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        dataInserter = new DataInserter(rollNoEditText.getText(), nameEditText.getText(),
                                        fatherEditText.getText(), feeEditText.getText());
        dataInserter.insertData();
        dataInserter = null;
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        rollNoEditText.setText("");
        nameEditText.setText("");
        fatherEditText.setText("");
        feeEditText.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ixClassPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ixClassPanelMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassesWindow("IX").setVisible(true);
            }
        });
    }//GEN-LAST:event_ixClassPanelMouseClicked

    private void ixIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ixIconMouseEntered
        
    }//GEN-LAST:event_ixIconMouseEntered

    private void ixClassPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ixClassPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ixClassPanelMouseEntered
    private void openCardWindow(JPanel selectedCard){
        cardsPanel.removeAll();
        cardsPanel.add(selectedCard);
        cardsPanel.repaint();
        cardsPanel.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeWindow().setVisible(true);
        });
    }
    
    public void gradient(){
        
    }
    
    private DataInserter dataInserter;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admissionButton;
    private javax.swing.JPanel admissionCardArea;
    private javax.swing.JPanel admissionCardPanel;
    private javax.swing.JSeparator admissionSeparator;
    private javax.swing.JPanel admissionTitleBar;
    private javax.swing.JPanel cardsAreaPanel;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JPanel classesButton;
    private javax.swing.JPanel classesCardPanel;
    private javax.swing.JLabel father;
    private javax.swing.JTextField fatherEditText;
    private javax.swing.JLabel fee;
    private javax.swing.JTextField feeEditText;
    private javax.swing.JPanel homeWindowMainPanel;
    private javax.swing.JLabel ixClass;
    private javax.swing.JPanel ixClassDetails;
    private javax.swing.JLabel ixClassName;
    private javax.swing.JPanel ixClassPanel;
    private javax.swing.JLabel ixIcon;
    private javax.swing.JPanel ixIconPanel;
    private javax.swing.JSeparator ixSeparator;
    private javax.swing.JLabel ixStudents;
    private javax.swing.JLabel ixStudentsNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel menuItemsPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameEditText;
    private javax.swing.JLabel rollNo;
    private javax.swing.JTextField rollNoEditText;
    private javax.swing.JButton submit;
    private javax.swing.JPanel titleBarPanel;
    private javax.swing.JLabel xClass;
    private javax.swing.JPanel xClassDetails;
    private javax.swing.JLabel xClassName;
    private javax.swing.JPanel xClassPanel;
    private javax.swing.JLabel xIcon;
    private javax.swing.JPanel xIconPanel;
    private javax.swing.JSeparator xSeparator;
    private javax.swing.JLabel xStudents;
    private javax.swing.JLabel xStudentsNumber;
    private javax.swing.JLabel xiPEClass;
    private javax.swing.JPanel xiPEClassDetails;
    private javax.swing.JLabel xiPEClassName;
    private javax.swing.JPanel xiPEClassPanel;
    private javax.swing.JLabel xiPEIcon;
    private javax.swing.JPanel xiPEIconPanel;
    private javax.swing.JSeparator xiPESeparator;
    private javax.swing.JLabel xiPEStudents;
    private javax.swing.JLabel xiPEStudentsNumber;
    private javax.swing.JLabel xiPMClass;
    private javax.swing.JPanel xiPMClassDetails;
    private javax.swing.JLabel xiPMClassName;
    private javax.swing.JPanel xiPMClassPanel;
    private javax.swing.JLabel xiPMIcon;
    private javax.swing.JPanel xiPMIconPanel;
    private javax.swing.JSeparator xiPMSeparator;
    private javax.swing.JLabel xiPMStudents;
    private javax.swing.JLabel xiPMStudentsNumber;
    private javax.swing.JLabel xiiPEClass;
    private javax.swing.JPanel xiiPEClassDetails;
    private javax.swing.JLabel xiiPEClassName;
    private javax.swing.JPanel xiiPEClassPanel;
    private javax.swing.JLabel xiiPEIcon;
    private javax.swing.JPanel xiiPEIconPanel;
    private javax.swing.JSeparator xiiPESeparator;
    private javax.swing.JLabel xiiPEStudents;
    private javax.swing.JLabel xiiPEStudentsNumber;
    private javax.swing.JLabel xiiPMClass;
    private javax.swing.JPanel xiiPMClassDetails;
    private javax.swing.JLabel xiiPMClassName;
    private javax.swing.JPanel xiiPMClassPanel;
    private javax.swing.JLabel xiiPMIcon;
    private javax.swing.JPanel xiiPMIconPanel;
    private javax.swing.JSeparator xiiPMSeparator;
    private javax.swing.JLabel xiiPMStudentNumber;
    private javax.swing.JLabel xiiPMStudents;
    // End of variables declaration//GEN-END:variables
   
}

